### ISSUE TITLE
!

### ISSUE THREAD

**Issue by Grecia1982** [idelsink/spotify-track-preview#11]

**Comment by idelsink** [comment]
Ah right, you don't need this feature anymore? I will close this issue then.

**Comment by Grecia1982** [comment]
MY FRIEND I WRITE ON COMMENTS!!!IS THAT WRONG???????

**Comment by Grecia1982** [comment]
MY FRIEND I AM NEW USER ON GITHUB!!!I DONT KNOW I HAVE TO WRITE MY COMMENT ON ISSUE OR ON COMMITS?

**Comment by idelsink** [comment]
Hello @Grecia1982,
It's good to hear that there are always new people joining this awesome community. 
First I recommend reading into what Github is: https://guides.github.com/activities/hello-world/

Comments on commits are usually reserved for a comment about the commit itself while Issues are usually used for new feature requests and overall issues regarding the project.

I would also recommend when creating an issue to be clear and precise in what you want to achieve. Use examples, clear language and be descriptive. 

I will close the comments for this issue, but you can always create a new issue if you see the need.
