### ISSUE TITLE
GREATTTTTTTTTTTTTT JOBBBBBBBBBBBBBBBBBBBBB!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Grecia1982** [idelsink/spotify-track-preview#12]
hello thereeeeeeeeee...many thankssssssssssss for this amazinggggggggggggggg web!!!but please I Think it will be much better if you make it load more songs every page!!!500 SONGS for example or more and will be greatttttttttttt if appear also genre and year for every song!!!this make your web the best of the best of the besttttttttttttttttt of apps and webs!!!pleaseeeeeeeeeeeee dudeeeeeeeee!!!Merry Christmas and God bless you!!!

**Comment by idelsink** [comment]
Hi @Grecia1982 could you please create an issue with a meaningful title and content? Something along the lines of 'Feature x and Y' with a more descriptive comment?
